name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  unit-tests:
    name: Go unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18.0-beta1'
      - name: Run Tests
        run: go test -race -v ./...
      - name: Run Vet
        run: go vet ./...
